version: '3'
services:
  # Build app from Dockerfile in same folder
  devops-g3-app-1:
    build: .

  # Build the db as name world from the Dockerfile in the db folder
  world:
    build: db/.
    # keep port forwarding so we can test app locally without docker
    ports:
      - "33060:3306"