name: A workflow for Airelux marketing analysis app
on: push

jobs:
  build:
    name: analysis action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package with Maven
        run: mvn package
      - name: Run docker compose
        run: docker compose up --abort-on-container-exit
      - name: view logs
        run: docker logs devops-g3-app-1
      - name: Copy Output
        run: docker container cp devops3-app-1:./tmp/output ./
               - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
