name: A workflow for Airelux marketing analysis app
on: push

jobs:
  UnitTests:
    name: Unit Test Build Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.napier.airelux.ReportSelectorTest test
      - name: List dirs
        run: |
          cd ./target/site/jacoco
          pwd
          ls
      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  #          directory: ./target/site/jacoco
  #          verbose: true # optional (default = false)
  IntegrationTests:
    name: Integration Test Build Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          docker build -t world ./db 
          docker run --name world -dp 33060:3306 world
          mvn -Dtest=com.napier.airelux.ReportSelectorIntegrationTest test
          docker stop world
          docker rm world
          docker image rm world
      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  Build:
    name: Build and Start Using docker-compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
      - name: view logs
        run: docker logs devops-g3-app-1


