name: Unit Test Workflow

on:
  push:
    branches:
      - master  # Specify the branch where this workflow should run
  pull_request:  # Trigger tests on pull requests
    branches:
      - master

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Run Unit Tests
      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.devops-g3.ReportSelector test
