1	name: A workflow for my App
2	on: push
  3
4	jobs:
5	  build:
6	    name: Test Build Action
7	    runs-on: ubuntu-20.04
8	    steps:
9	      - name: Checkout
10	        uses: actions/checkout@v4
11	      - name: Set up JDK 17
12	        uses: actions/setup-java@v4
13	        with:
14	          java-version: '17'
15	          distribution: 'adopt'
16	      - name: Unit Tests
17	        run: mvn -Dtest=com.napier.airelux.ReportSelectorTest.ReportSelector test
18	      - name: Package and Run docker compose
19	        run: |
  20	          mvn package -DskipTests
  21	          docker compose up --abort-on-container-exit